title: MyL4bSec
description: Security Blog

url: https://myl4bsec.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: myl4bsec
   twitter: imisaacbatista
   facebook: isaac.batista.142
   email: isaac3366@gmail.com

google_analytics: "UA-58263416-1"
